#%RAML 1.0 NamedExample
value: | 
  [
    {
      "Date_du_dernier_consentement__pc": "2020-05-17",
      "Dernier_canal_de_consentement__pc": "2020-05-17",
      "NAdherent__c"  : "14523", 
      "Salutation" : "Mme", 
      "FirstName" : "mak1789", 
      "LastName" : "mak7412", 
      "NomMarital__c"  : "test4", 
      "CSP__c"  : "Artisans", 
      "PersonBirthdate" : "2020-05-17", 
      "SituationMatrimoniale__c"  : "Veuve", 
      "NombreDEnfantsACharge__c"  : "2", 
      "StatutDuCompteClient__c"  : "test6", 
      "TypeDeCompte__c"  : "Client", 
      "PersonHomePhone" : "7854174123", 
      "PersonOtherPhone" : "8563278965", 
      "PersonMobilePhone" : "7412541257", 
      "PersonEmail" : "test14785@test.com", 
      "BillingAddress" : "", 
      "PersonMailingAddress" : "", 
      "RaisonSociale1__c"  : "test7", 
      "AdresseComplementaire1__c"  : "test8", 
      "AdresseComplementaire1N2__c"  : "test9", 
      "ShippingAddress" : "", 
      "AdresseComplementaire2__c"  : "test10", 
      "RaisonSociale2__c"  : "test11", 
      "AdresseComplementaire2N2__c"  : "test12", 
      "NPAIAdresse1__pc" : "test13", 
      "NPAIAdresse2__c"  : "test14", 
      "SegmentMarketing__c"  : "test15", 
      "PartenaireDeDistribution__c"  : "test16", 
      "DateDeDeces__c"  : "2023-05-17", 
      "Profession__c"  : "POTIER", 
      "Industry" : "Ouvriers", 
      "PrCommercialesInfosServicesProduits__pc"  : "Email", 
      "Newsletter__pc"  : "test22",
      "Id" : "0011q00000jcFitAAE",
      "EnqueteClient__pc": "test",
      "EnvoiDeContenusAdaptes__pc": "test",
      "ShippingStreet": "shipping street",
      "ShippingPostalCode": "postal code",
      "ShippingCity": "city",
      "ShippingState": "state",
      "ShippingCountry": "country",
      "BillingStreet": "billing street",
      "BillingPostalCode": "billing postal code",
      "BillingCity": "billing city",
      "BillingState": "billing state",
      "BillingCountry": "billing country"
    },
    {
      "Date_du_dernier_consentement__pc": "2020-05-17",
      "Dernier_canal_de_consentement__pc": "2020-05-17",
      "NAdherent__c"  : "14523", 
      "Salutation" : "Mme", 
      "FirstName" : "mak1789", 
      "LastName" : "mak7412", 
      "NomMarital__c"  : "test4", 
      "CSP__c"  : "Artisans", 
      "PersonBirthdate" : "2020-05-17", 
      "SituationMatrimoniale__c"  : "Veuve", 
      "NombreDEnfantsACharge__c"  : "2", 
      "StatutDuCompteClient__c"  : "test6", 
      "TypeDeCompte__c"  : "Client", 
      "PersonHomePhone" : "7854174123", 
      "PersonOtherPhone" : "8563278965", 
      "PersonMobilePhone" : "7412541257", 
      "PersonEmail" : "test14785@test.com", 
      "BillingAddress" : "", 
      "PersonMailingAddress" : "", 
      "RaisonSociale1__c"  : "test7", 
      "AdresseComplementaire1__c"  : "test8", 
      "AdresseComplementaire1N2__c"  : "test9", 
      "ShippingAddress" : "", 
      "AdresseComplementaire2__c"  : "test10", 
      "RaisonSociale2__c"  : "test11", 
      "AdresseComplementaire2N2__c"  : "test12", 
      "NPAIAdresse1__pc" : "test13", 
      "NPAIAdresse2__c"  : "test14", 
      "SegmentMarketing__c"  : "test15", 
      "PartenaireDeDistribution__c"  : "test16", 
      "DateDeDeces__c"  : "2023-05-17", 
      "Profession__c"  : "POTIER", 
      "Industry" : "Ouvriers", 
      "PrCommercialesInfosServicesProduits__pc"  : "Email", 
      "Newsletter__pc"  : "test22",
      "Id" : "",
      "EnqueteClient__pc": "test",
      "EnvoiDeContenusAdaptes__pc": "test",
      "ShippingStreet": "shipping street",
      "ShippingPostalCode": "postal code",
      "ShippingCity": "city",
      "ShippingState": "state",
      "ShippingCountry": "country",
      "BillingStreet": "billing street",
      "BillingPostalCode": "billing postal code",
      "BillingCity": "billing city",
      "BillingState": "billing state",
      "BillingCountry": "billing country"
    }
  ]